services:
  api:
    image: cne_api
    environment:
      POSTGRES_DATABASE: cne
      POSTGRES_HOST: /run/secrets/postgres_host
      POSTGRES_PORT: /run/secrets/postgres_port
      POSTGRES_USERNAME: /run/secrets/postgres_username
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
    ports:
      - "8599:8595"   # left side is the host port (external), right side is the container port (internal, used by UI)
    secrets:
      - postgres_host
      - postgres_port
      - postgres_username
      - postgres_password
  ui:
    image: cne_ui
    ports:
      - "8095:8095"
    environment:
      API_HOST: api
      API_PORT: 8595
      CNE_YEAR: ${CNE_YEAR}
    depends_on:
      api:
        condition: service_started

# noinspection ComposeUnknownKeys
secrets:
  postgres_host:
    environment: POSTGRES_HOST
  postgres_port:
    environment: POSTGRES_PORT
  postgres_username:
    environment: POSTGRES_USERNAME
  postgres_password:
    environment: POSTGRES_PASSWORD
