name: cne
channels:
  - anaconda
  - conda-forge
  - main
dependencies:
  - ca-certificates
  - certifi
  - fastapi[version='>=0.115,<1']
  - matplotlib[version='>=3.9,<4']
  - numpy[version='>=2.1,<3']
  - openssl
  - pandas[version='>=2.2,<3']
  - pandera[version='>=0.20','<1']
  - pip
  - plotly[version='>=5.20,<6']
  - psycopg[version='>=3.2,<3.3']
  - pydantic[version='>=2']
  - pydantic-extra-types
  - pylint
  - pypdf
  - python[version='>=3.12.5,<3.13']
  - seaborn[version='>=0.13,<1']
  - streamlit=1.40
  - pip:
      - streamlit-extras
