name: cne
channels:
  - anaconda
  - conda-forge
  - main
dependencies:
  - ca-certificates[version='>=2024.8']
  - certifi[version='>=2024.8']
  - fastapi[version='>=0.115,<1']
  - matplotlib[version='>=3.9,<4']
  - numpy[version='>=2.1,<3']
  - openssl[version='>=3.3,<4']
  - pandas[version='>=2.2,<3']
  - pandera[version='>=0.20','<1']
  - pip[version='>=24.2,<25']
  - plotly[version='>=5.24,<6']
  - psycopg[version='>=3.2,<3.3']
  - pydantic[version='>=2.8','<3']
  - pydantic-extra-types[version='>=2.8','<3']
  - pypdf[version='>=4.2,<5']
  - python[version='>=3.12.7,<3.13']
  - seaborn[version='>=0.13,<1']
  - streamlit[version='>=1.40']
  - pip:
      - streamlit-extras
